language: python

python:
  - 3.6
  - 3.7
  - 3.8
  - nightly

install:
  - pip install -r requirements/ci.txt

script:
  - pytest --cov-report term --cov=iko .

after_success:
  - codecov

jobs:
  include:
    - stage: lint
      python: 3.7
      script: flake8

stages:
  - lint
  - test

